### ISSUE TITLE
getRedirection always returns english object

### ISSUE THREAD

**Issue by letaptravek** [Exorth98/react-native-translation#2]
Hello,

I am not able to get raw translations to work using getRedirection. Is it the right way to load translation object per language and access throughout the App. Can you please help?.

Thanks for your help.

**App.js**

```javascript
import {LanguageProvider} from 'react-native-translation';
const locale = 'fr-FR';//Localization.locale;
export default class App extends React.Component {
  render() {
    return (
      <LanguageProvider language={locale}>
        <AppNavigator/>
      </LanguageProvider>
    );
  }
}
```

**en.js**
`export default {
  hello: "Hello"
};
`
**fr.js**
`export default {
  hello: "Bonjour"
};
`

**transRedirector.js**
```javascript
import en from "./locales/en";
import fr from "./locales/fr";

const transRedirector = {
  "en-US" : en,
  "fr-FR" : fr
}

export default transRedirector;`
```
**Main.js**

```javascript
import {getTranslation, getRedirection} from 'react-native-translation';
import transRedirector from './helpers/transRedirector';
const transdata = getRedirection(transRedirector);
```

Output of transdata

`{"hello":"Hello"}`

**Comment by Exorth98** [comment]
Hello @letaptravek!

It seems like you are trying to access the context outside a component.
In your `main.js`, you have to use the `getRedirection()` function **inside a component**, so it can access the context where the language is stored.

For a full explanation:

The package uses the React Context API, that defines a 'context' to provide the language everywhere in the app. 
You set this context with the `LanguageProvider` component, and this context is defined for every child **component**.

The `getRedirection()` function needs to access the context to access the current language. This is why it has to be called **inside a child component of the provider**.


Concretely, here is a simple snack.io showing how to solve your issue:
[https://snack.expo.io/@exorth/quiet-popsicle](https://snack.expo.io/@exorth/quiet-popsicle)


Don't hesitate if you're facing any other issue.

**Comment by letaptravek** [comment]
Hello @Exorth98!, It's works now. I used outside the component.   Thank you!

**Comment by letaptravek** [comment]
Hello @Exorth98 ,

Is it possible to use getRedirection in App.js as below. I am not able to get this work.

Thanks

```javascript
import * as React from 'react';
import {LanguageProvider, getRedirection} from 'react-native-translation';
import transRedirector from './src/helpers/transRedirector';
const locale = 'fr-FR';//Localization.locale;

export default class App extends React.Component {
  render() {
  const transdata = getRedirection(transRedirector); 
    return (
      <LanguageProvider language={locale} translations = {transdata}>
        <Main/>
      </LanguageProvider>
    );
  }
}
```

**Comment by Exorth98** [comment]
Hey @letaptravek,

No you can't, for the same reason explained before:
The `getRedirection()` has to access the language which is in the context. And the context is defined only for the children components of the `<LanguageProvider>`.

Geneally speaking, the package doesn't have a  _1 language per file_ feature for the moment.
Which is what you're trying to do with the Redirection.

That's actually a interesting way to build it with the actual tools, but it is not compatible with the use of the `translations `prop of the `<LanguageProvider>`.

However, such a feature it will be soon implemented in the package.

**Comment by letaptravek** [comment]
No Problem, Thanks
